project:
  type: book
  output-dir: docs

book:
  title: "Untitled Lean Thesis"
  author:
    - name: Logan Johnson
  page-footer: "Logan Johnson 2023"
  downloads: pdf
  chapters:
    - index.qmd
    - Chap1.qmd
    - Chap2.qmd
    - Chap3.qmd
    - Chap4.qmd
    - Chap5.qmd
    - Chap6.qmd

format:
  html:
    theme: cosmo
    css: HTPIwLstyles.css
    syntax-definitions: [lean.xml,state.xml]
    toc-depth: 2
    toc-title: In This Chapter
    number-depth: 0
    include-before-body: mathjaxdefs.tex
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    number-depth: 0
    syntax-definitions: [lean.xml,state.xml]
    include-in-header: inpreamble.tex
    include-before-body: thmdefs.tex
    monofont: JuliaMono
    keep-tex: true
    date: \small Georgetown College

filters:
  - latex-environment
environments: [quote, ind, inpt, outpt, bef, aft, numex, mdsk, thm, nthm, dfn, ndfn, npf, absnobreak]
commands: excl
